---
- hosts: ubuntu_ssh_i
  tasks:
  - name: Actualizar repositorios -> "apt update"
    apt: 
        update-cache: yes
  - name: Instalar Nginx -> "apt install nginx"
    apt: name=nginx state=present
  - name: Copiar sitio web React+Vite
    copy:
        src: /home/feli/Documentos/docker_volumes/dist/
        dest: /var/www/sa_practica1
  - name: Crear archivo de configuración en Nginx para el sitio web copiado
    copy:
        dest: /etc/nginx/sites-enabled/sa_practica1
        content: "server {
                        listen 80;
                        listen [::]:80;
  
                        #server_name example.ubuntu.com;

                        root /var/www/sa_practica1;
                        index index.html;

                        location / {
                                try_files $uri $uri/ =404;
                        }
                  }"
  - name: Eliminar archivo 'default' en sites-enabled para eliminar el sitio predeterminado de Nginx
    ansible.builtin.file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  - name: Reiniciar servicio de Nginx
    service: name=nginx state=started
...